/*"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header";
import { Sidebar } from "@/app/components/sidebar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);  // Manage sidebar state

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          {/* Sidebar */
         /* <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />

          {/* Main Content Area */
          /*<div className="flex-1 flex flex-col overflow-hidden">
            {/* Header */
           /* <Header sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
            
            {/* Page Content */
          //  <main className="flex-grow p-6 bg-gray-100 dark:bg-gray-900 overflow-y-auto">
             // {children}
           // </main>
          //</div>
        //</div>
     // </body>
   // </html>
  //);
//}
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DashboardLayout from "@/app/dashboard/layout"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardLayout children={undefined}/>
        {children}
      </body>
    </html>
  );
}
